### ISSUE TITLE
Creation of dynamic property is deprecated

### ISSUE THREAD

**Issue by FaycalBoutam** [barn2plugins/document-library-lite#8]
### Full description

> There seem to be a few warning popping up when using the Lite version - nothing seems to be broken yet but just wondering if these can be fixed easily to avoid any issues going forward.
> 
> Deprecated: Creation of dynamic property Barn2\Plugin\Document_Library\Document::$post_object is deprecated in ...\public\wp-content\plugins\document-library-lite\src\Document.php on line 36

They must be using PHP 8.2 where dynamic properties are deprecated:
https://php.watch/versions/8.2/dynamic-properties-deprecated

### Ticket link

https://secure.helpscout.net/conversation/2703952654/117228?viewId=7855239

**Comment by ejpadero** [comment]
Hi, @amirition. I know you're currently OOO, so am just bumping this up for when you're back. Thanks!

**Comment by alessandrotesoro** [comment]
For some reason I was getting notifications regarding issues in this repository, so anyways, because Amir is away and the next release is under QA and has quite a few bugs/tasks reported by Aleem. I just pushed a PR that fixes this hoping to help speed things up a tiny bit.

Please include this in the next release @amirition

**Comment by amirition** [comment]
resolved in version 1.1.0.
